name: Lab Build

on: [push]

jobs:
  lab1Build:
    name: build
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: make lab1
      working-directory: ./lab1
      run: make
    
    - uses: actions/checkout@v1
    - name: make lab2
      working-directory: ./lab2
      run: make
    
    - uses: actions/checkout@v1
    - name: make lab2_2
      working-directory: ./lab2_2
      run: make
      
    - uses: actions/checkout@v1
    - name: buildCovReport
      working-directory: ./lab2_2
      run: |
        g++ -coverage -O0 -pthread message.c client.c -o client
        g++ -coverage -O0 -pthread message.c clientInfo.c server.c -o server
        gcov message.c
        gcov client.c
        gcov clientInfo.c
        gcov server.c
        chmod 710 client
        chmod 710 server
        ./server 5000
        ./client

    - uses: codecov/codecov-action@v1
      with:
        name: ECE361Codecov
        token: 2236bb39-b343-4d45-a35e-21148c233c0c
