name: C/C++ CI

on: [push]

jobs:
  build:
    name: build_lab1
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      working-directory: ./lab1
      run: make
